version: '3.8'
services:

  database:
    image: postgres:14.1-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=customers
    ports:
      - '5432:5432'
    networks:
      - network-registration

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    networks:
      - network-registration
      - network-notification

  registration:
    build: ./customer-registration
    ports:
      - '8080:8080'
    depends_on:
      - database
      - rabbitmq
    restart: on-failure
    networks:
      - network-registration

  notification:
    build: ./customer-notification
    depends_on:
      - rabbitmq
    restart: on-failure
    networks:
      - network-notification

networks:
  network-registration:
  network-notification: